### PR TITLE
Custom topic support

### PR DESCRIPTION
**Pull request by belucid**
https://trello.com/c/1CaoeZfD

This PR adds the ability for the API to work with custom topics, in addition to the ones we already know about. It also removes the section `icon` property which is no longer used.

To test:

- [x] Review the code and tests, code does the desired and tests test the same?
- [x] Tests pass?
- [x] Reimport Bago sample data.
- [x] Look at Bago in the UI. All there? Content good? Can you still edit it? Archive it?
- [x] PATCH a new custom topic to Blank with: 

```
curl --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyLWlkIjoic2xhY2s6VTA2U0JUWEpSIiwibmFtZSI6IlNlYW4gSm9obnNvbiIsInJlYWwtbmFtZSI6IlNlYW4gSm9obnNvbiIsImF2YXRhciI6Imh0dHBzOlwvXC9zZWN1cmUuZ3JhdmF0YXIuY29tXC9hdmF0YXJcL2Y1YjhmYzFhZmZhMjY2YzgwNzIwNjhmODExZjYzZTA0LmpwZz9zPTE5MiZkPWh0dHBzJTNBJTJGJTJGc2xhY2suZ2xvYmFsLnNzbC5mYXN0bHkubmV0JTJGN2ZhOSUyRmltZyUyRmF2YXRhcnMlMkZhdmFfMDAyMC0xOTIucG5nIiwiZW1haWwiOiJzZWFuQG9wZW5jb21wYW55LmNvbSIsIm93bmVyIjpmYWxzZSwiYWRtaW4iOnRydWUsIm9yZy1pZCI6InNsYWNrOlQwNlNCTUg2MCJ9.9Q8GNBojQ_xXT0lMtKve4fb5Pdh260oc2aUc-wP8dus" \
-i -X PATCH \
--header "Accept: application/vnd.open-company.company.v1+json" \
--header "Accept-Charset: utf-8" \
--header "Content-Type: application/vnd.open-company.company.v1+json" \
-d '{"sections": {"company":[], "progress": ["custom-1234"]}, "custom-1234": {"title":"t","headline":"","body":""}}' \
http://localhost:3000/companies/blank-inc
```
- [x] Look at Blank's dashboard in the web UI: [http://localhost:3559/blank-inc](http://localhost:3559/blank-inc). Topic there? Content there (why is the title missing, was set as `t` in the PATCH)? Can you still edit it? Can archive it? 
- [ ] Merge
- [ ] Deploy

### CODE REVIEW

**Comment by bago2k4** [comment]
reviewing, will wait for conflicts resolution before i merge this

**Comment by bago2k4** [comment]
@belucid while using this for the UI side i discovered that a newly added custom section has not an updated-at property. the UI, right now, requires one to display the section properly, do you think we can add it?

**Comment by belucid** [comment]
Yep @bago2k4 I'll add it.

Can you merge `mainline` in?

**Comment by bago2k4** [comment]
reviewing

**Comment by bago2k4** [comment]
@belucid i get a 422 when PATCHing the company data with a new section (even not custom sections).
request from console:
```
curl --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyLWlkIjoic2xhY2s6VTA2U0JUWEpSIiwibmFtZSI6IlNlYW4gSm9obnNvbiIsInJlYWwtbmFtZSI6IlNlYW4gSm9obnNvbiIsImF2YXRhciI6Imh0dHBzOlwvXC9zZWN1cmUuZ3JhdmF0YXIuY29tXC9hdmF0YXJcL2Y1YjhmYzFhZmZhMjY2YzgwNzIwNjhmODExZjYzZTA0LmpwZz9zPTE5MiZkPWh0dHBzJTNBJTJGJTJGc2xhY2suZ2xvYmFsLnNzbC5mYXN0bHkubmV0JTJGN2ZhOSUyRmltZyUyRmF2YXRhcnMlMkZhdmFfMDAyMC0xOTIucG5nIiwiZW1haWwiOiJzZWFuQG9wZW5jb21wYW55LmNvbSIsIm93bmVyIjpmYWxzZSwiYWRtaW4iOnRydWUsIm9yZy1pZCI6InNsYWNrOlQwNlNCTUg2MCJ9.9Q8GNBojQ_xXT0lMtKve4fb5Pdh260oc2aUc-wP8dus" \
-i -X PATCH \
--header "Accept: application/vnd.open-company.company.v1+json" \
--header "Accept-Charset: utf-8" \
--header "Content-Type: application/vnd.open-company.company.v1+json" \
-d '{"sections": {"company":[], "progress": ["custom-1234"]}, "custom-1234": {"title":"t","headline":"","body":""}}' \
http://localhost:3000/companies/blank-inc
```
response:
```
bago@iacopos-MacBook-Pro:open-company-web (custom-topics)*
$ curl --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyLWlkIjoic2xhY2s6VTA2U0JUWEpSIiwibmFtZSI6IlNlYW4gSm9obnNvbiIsInJlYWwtbmFtZSI6IlNlYW4gSm9obnNvbiIsImF2YXRhciI6Imh0dHBzOlwvXC9zZWN1cmUuZ3JhdmF0YXIuY29tXC9hdmF0YXJcL2Y1YjhmYzFhZmZhMjY2YzgwNzIwNjhmODExZjYzZTA0LmpwZz9zPTE5MiZkPWh0dHBzJTNBJTJGJTJGc2xhY2suZ2xvYmFsLnNzbC5mYXN0bHkubmV0JTJGN2ZhOSUyRmltZyUyRmF2YXRhcnMlMkZhdmFfMDAyMC0xOTIucG5nIiwiZW1haWwiOiJzZWFuQG9wZW5jb21wYW55LmNvbSIsIm93bmVyIjpmYWxzZSwiYWRtaW4iOnRydWUsIm9yZy1pZCI6InNsYWNrOlQwNlNCTUg2MCJ9.9Q8GNBojQ_xXT0lMtKve4fb5Pdh260oc2aUc-wP8dus" \
> -i -X PATCH \
> --header "Accept: application/vnd.open-company.company.v1+json" \
> --header "Accept-Charset: utf-8" \
> --header "Content-Type: application/vnd.open-company.company.v1+json" \
> -d '{"sections": {"company":[], "progress": ["custom-1234"]}, "custom-1234": {"title":"t","headline":"","body":""}}' \
> http://localhost:3000/companies/blank-inc
HTTP/1.1 422 Unprocessable Entity
Content-Type: text/plain;charset=utf-8
Vary: Accept, Accept-Charset
X-Liberator-Trace-Id: 8wnwa
Link: <//x-liberator/requests/8wnwa>; rel=x-liberator-trace
X-Liberator-Trace: :decision (:initialize-context {:jwtoken "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyLWlkIjoic2xhY2s6VTA2U0JUWEpSIiwibmFtZSI6IlNlYW4gSm9obnNvbiIsInJlYWwtbmFtZSI6IlNlYW4gSm9obnNvbiIsImF2YXRhciI6Imh0dHBzOlwvXC9zZWN1cmUuZ3JhdmF0YXIuY29tXC9hdmF0YXJcL2Y1YjhmYzFhZmZhMjY2YzgwNzIwNjhmODExZjYzZTA0LmpwZz9zPTE5MiZkPWh0dHBzJTNBJTJGJTJGc2xhY2suZ2xvYmFsLnNzbC5mYXN0bHkubmV0JTJGN2ZhOSUyRmltZyUyRmF2YXRhcnMlMkZhdmFfMDAyMC0xOTIucG5nIiwiZW1haWwiOiJzZWFuQG9wZW5jb21wYW55LmNvbSIsIm93bmVyIjpmYWxzZSwiYWRtaW4iOnRydWUsIm9yZy1pZCI6InNsYWNrOlQwNlNCTUg2MCJ9.9Q8GNBojQ_xXT0lMtKve4fb5Pdh260oc2aUc-wP8dus", :user {:user-id "slack:U06SBTXJR", :name "Sean Johnson", :real-name "Sean Johnson", :avatar "https://secure.gravatar.com/avatar/f5b8fc1affa266c8072068f811f63e04.jpg?s=192&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F7fa9%2Fimg%2Favatars%2Fava_0020-192.png", :email "sean@opencompany.com", :owner false, :admin true, :org-id "slack:T06SBMH60"}})
X-Liberator-Trace: :decision (:service-available? true)
X-Liberator-Trace: :decision (:known-method? :patch)
X-Liberator-Trace: :decision (:uri-too-long? false)
X-Liberator-Trace: :decision (:method-allowed? :patch)
X-Liberator-Trace: :decision (:malformed? [false {:data {:sections {:company [], :progress ["custom-1234"]}, :custom-1234 {:title "t", :headline "", :body ""}}}])
X-Liberator-Trace: :decision (:authorized? true)
X-Liberator-Trace: :decision (:allowed? true)
X-Liberator-Trace: :decision (:valid-content-header? true)
X-Liberator-Trace: :decision (:known-content-type? true)
X-Liberator-Trace: :decision (:valid-entity-length? true)
X-Liberator-Trace: :decision (:is-options? false)
X-Liberator-Trace: :decision (:accept-exists? true)
X-Liberator-Trace: :decision (:media-type-available? {:representation {:media-type "application/vnd.open-company.company.v1+json"}})
X-Liberator-Trace: :decision (:accept-language-exists? nil)
X-Liberator-Trace: :decision (:accept-charset-exists? "utf-8")
X-Liberator-Trace: :decision (:charset-available? {:representation {:charset "utf-8"}})
X-Liberator-Trace: :decision (:accept-encoding-exists? nil)
X-Liberator-Trace: :decision (:processable? [false {:reason {:public missing-required-key}}])
X-Liberator-Trace: :handler (:handle-unprocessable-entity)
Content-Length: 47
Server: http-kit
Date: Sun, 05 Jun 2016 16:53:44 GMT

Not processable: {:public missing-required-key}
```

**Comment by bago2k4** [comment]
@belucid never mind, i forgo to reimport black-inc data before adding the section

**Pull request merged**
