### PR TITLE
Stakeholder Updates via Bot

### PR DESCRIPTION
**Pull request by martinklepsch**
Review with https://github.com/open-company/open-company-bot/pull/9 — [trello card](https://trello.com/c/qa0oG1yl/416-slack-share-snapshot-end-to-end-api-bot)

**Test instructions in other PR**

### CODE REVIEW

**Comment by belucid** [comment]
Just a heads up @martinklepsch  tests are failing

**Comment by belucid** [comment]
@martinklepsch #43 is closed, is this ready for review?

**Comment by belucid** [comment]
Reviewing.

**Comment by martinklepsch** [comment]
👍🎉

**Comment by belucid** [comment]
Seriously!

**Pull request merged**
