### PR TITLE
Bad slugs = 404s, not 500s

### PR DESCRIPTION
**Pull request by belucid**
https://trello.com/c/UANMoEVb

Ensure bad slugs (org, board, topic, and update slugs) give us 404s in API calls, not 500s.

Slugs in question are: org, board, topic, update

**Testing:**

For the positive case, getting a 404 rather than a 500, the main test is to review the code. 

You can also test it with the UI client w/ upper case slugs in the old client when it still allowed that. You can further try it with made up slugs with _ rather than -. These are invalid and would have 500'd but not 404.

I tested all the 500 cases though and watched them turn into 404's as I made the changes, so I'm not so worried about the positive cases (it's really just code hygiene anyway, these call w/ bad slugs shouldn't be made).

The main testing effort here is regression testing. Want to make sure nothing broke. So exercise the client broadly against this branch doing all the usual activities once: create org, create board, create topic, create entry, remove entry, archive topic, create update, board settings, org settings, anything else you can think of against the storage API. Make sure nothing broke.

### CODE REVIEW

**Comment by bago2k4** [comment]
@belucid conflicts here, it needs your attention

**Comment by belucid** [comment]
@bago2k4 resolved.

**Comment by bago2k4** [comment]
reviewing

**Comment by bago2k4** [comment]
@belucid I'm getting
`Assert failed: (or (lib-schema/unique-id? identifier) (slug/valid-slug? identifier))`
when i GET the entry point with the requested org as params: http://localhost:3559/?requested=UPPERCASE
it fails for any invalid slug: `/UpperCase`, `/Upper_Case` etc...

**Comment by bago2k4** [comment]
if you want to test with the client checkout `staging-deploy` branch and comment out lines from 80 to 83 of src/oc/web/core.cljs

**Comment by belucid** [comment]
Great catch @bago2k4 !

Fix is in.

**Comment by bago2k4** [comment]
@belucid even if i'm the admin of the team and i'm listed as author in both org and board i don't see any edit link (POST, PUT or PATCH) when i GET the org and the board data. More details in Slack.
The org is 18f freshly imported using mainline before switching to this branch.

**Comment by belucid** [comment]
@bago2k4 this is ready for you again.

**Pull request merged**
