### PR TITLE
initial bot integration

### PR DESCRIPTION
**Pull request by martinklepsch**
[Trello](https://trello.com/c/f0dln1Pi/134-initial-slackbot) — Review with https://github.com/open-company/open-company-auth/pull/3 (merged)

This adds the basic skeleton of integrating with our bot.

- If a company is created by a Slack org owner the bot will initiate a DM
  conversation with that user
- If a non-owner creates a company no conversation will be triggered

In the future we should expand the auth tokens to include the necessary bot tokens
no matter if the actual user is an owner or not. (Discussed [on Slack](https://opencompanyio.slack.com/files/martin/F17NXD6GZ/Slack_Authentication_Flow))

Testing setup (perhaps easiest done on staging):

- Update the `aws-*` keys in `config.edn` (bot) and `project.clj` (api) to contain valid credentials and an existing SQS queue.
- Run auth branch as above locally, run API branch locally, run bot locally.

Then do actual testing:

- Log Out
- Log In (now you should have an updated auth token)
- Create a new company
- The bot should talk to you to confirm some basic information
- Reply with `no` to one of it's questions and update data that way
- Check that the bot tells you that information has been updated

### CODE REVIEW

**Comment by martinklepsch** [comment]
@belucid CI is failing because of Kibit. 

- Is there any way to tell kibit to leave threading macros as they are? 
- Can we maybe move the Kibit/Eastwood stuff in a separate check so that it's easier to see on Github if it was Kibit or actual tests?

**Comment by belucid** [comment]
@martinklepsch Well this seems like a reasonable suggestion from Kibit:

Consider using:
  (:body @(slack :users.list {:token tkn}))
instead of:
  (-> @(slack :users.list {:token tkn}) :body)

**Comment by belucid** [comment]
@martinklepsch As far as I know GitHub can't deal w/ different Travis CI on the same commit. It can have multiple CI's configured though. So what we could do I guess is use Travis and Circle and configure tests on one and Kibit/Eastwood on the other.

**Comment by martinklepsch** [comment]
Right, this I agree with but then again it's inside a `(comment)` form — to me it seems stuff in there shouldn't break the build.

**Comment by belucid** [comment]
@martinklepsch Yeah, I bet Kibit would take a PR ignoring code in `(comment )` forms.

**Comment by martinklepsch** [comment]
I changed the stuff in the comment form but that still leaves us with the other thing — what do we do with that)/

**Comment by martinklepsch** [comment]
I changed the stuff in the comment form but that still leaves us with the other thing — what do we do with that?

**Comment by belucid** [comment]
@martinklepsch Right now it's failing on Eastwood due to unused namespaces:

```
src/open_company/lib/bot.clj:1:1: unused-namespaces: Namespace manifold.deferred is never used in open-company.lib.bot
src/open_company/lib/bot.clj:1:1: unused-namespaces: Namespace aleph.http is never used in open-company.lib.bot
```

**Comment by martinklepsch** [comment]
@belucid updated

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@martinklepsch deploying this branch on staging or prod breaks Slack auth'ing for some reason. You end up with:

```
https://staging.opencompany.com/login?access=Attempting%20to%20call%20unbound%20fn:%20#'amazonica.aws.s3/does-object-exist
```

**Comment by belucid** [comment]
@martinklepsch please merge in mainline

**Comment by martinklepsch** [comment]
@belucid done. The error you've given is coming from `auth` so I'm not sure if this branch really is the reason or if it slipped through in the auth PRs. Looking into it.

**Comment by belucid** [comment]
@martinklepsch tests are failing

**Comment by martinklepsch** [comment]
@belucid seems to be a transient issue, restarted the build without modification, all tests passed: https://travis-ci.org/open-company/open-company-api/builds/135608861

Looking at the error it seems to be while loading a library so likely not related to any tested functionality.

**Comment by martinklepsch** [comment]
@bago2k4 ready again (creating companies should now work again)

**Comment by martinklepsch** [comment]
There's an outstanding issue with this which I discovered yesterday: somehow after updating a company name two PATCH requests are made. The second request times out causing the conversation to turn into an error state. I'll try figuring out why that happens but I'm not sure when today I'll have a connection again (going to a family thing).

This also blocks #52.

**Pull request merged**
