### PR TITLE
routing changes

### PR DESCRIPTION
**Pull request by martinklepsch**
- trello card: https://trello.com/c/OfCMnDsC/343-routing-changes

### To Test:

- Run tests
- Try creating a company called `about` or `api` or any of the other reserved slugs, notice that the resulting slug gets modified (a  number is appended)
- look over the other modifications which allow customizing `/companies` for logged in users

### Discussion

1. Should we keep the code to customize `/companies`? Since all the redirect-on-login stuff only depends on what the entry point returns those changes are not strictly required. I think they might be useful in the future though. We can keep the new code and also keep the old behavior if that's wanted.

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@martinklepsch let's remove the customizations of /companies. I'd rather keep things cleaner and simpler than have that code around "in case we need it someday".

**Comment by martinklepsch** [comment]
@belucid I removed all the api customization, but I'd suggest to keep `company-links*`: it's more generic and function calls now make it very clear what links will be included. Also it's tested and has a similar footprint code-size wise.

**Comment by belucid** [comment]
Reviewing.

**Pull request merged**
