### PR TITLE
Update handling of Growth placeholder section

### PR DESCRIPTION
**Pull request by belucid**
https://trello.com/c/ro7Miff6

Review with https://github.com/open-company/open-company-web/pull/105

To test:

- [x] Reimport your data so you have no SU's
- [x] Look at the API response to /buffer/sections/new, should see it has a blank `:metrics` array and the standard metrics are now in `:standard-metrics` and they have descriptions.
- [x] Create a new company, look at the API response to `/<company>`, you should see the Growth placeholder section has an empty `:metrics` array and no `:interval` or `:units` array. Before this would have a full `:metrics` array and these other keys.
- [ ] Add a new Growth topic to a company that never had one, placeholder should look the same as described above.
- [x] Import Buffer. It should import OK, and the Growth topic data should have descriptions in it.

### CODE REVIEW

**Comment by bago2k4** [comment]
reviewing...

**Comment by bago2k4** [comment]
@belucid couple of problems here:
- if I create a new company :metrics is empty and that's good. but i can see :intervals that contains the list of allowed intervals and :units with the allowed units (not sure :intervals and :units are going to be a problem though, they can be there since the standard growth sections has interval and unit data saved inside the metrics array)
- I added a growth section to Blank Inc. and i get a 422 when i PATCH :sections with this response:
`Not processable: {:stakeholder-update {:outro disallowed-key, :title disallowed-key}}`, should i reimport the blank inc data?

**Comment by belucid** [comment]
@bago2k4 Yes, this is a branch off mainline so it knows nothing of SUs. If you reimport Blank you PATCH should be OK.

**Comment by belucid** [comment]
@bago2k4 New commit addresses the first bullet.

**Comment by belucid** [comment]
@bago2k4 this is ready for you to look at again.

**Comment by bago2k4** [comment]
@belucid seems that everything is working as expected. one side note though: in the unchecked item you say that the content should be like described in the 3rd point but i don't see default-metrics, i see an empty metric though. is that correct? if so we can merge this

**Pull request merged**
