### PR TITLE
Fix to PUT response

### PR DESCRIPTION
**Pull request by belucid**
https://trello.com/c/hJ9yLZEC

The responses from a PUT update of a company or a report would still have properties that were removed from the update. This adds failing integration tests for both company and report, and then fixes that so they pass. It also refactors and DRYs the tests some.

The key fixes are in `open-company.api.companies` and `open-company.api.reports`. Study those.

To test:

Note the new integration update tests for report and company. Study them and convince yourself they test the problem. Then run the tests!

```console
lein test!
```

They pass? Shazam!

Still not convinced. Checkout the updated cURL examples in the README. Run those against mainline, see the bug? Now switch back to this branch and run them again. See the fix? Holy boogers, that's good stuff. Merge it.

### CODE REVIEW

**Comment by bago2k4** [comment]
@belucid looks good, tests run fine, merging.
there is a thing that i don't quiet understand though: where the _:updated-company_ and _:updated-report_ come from? i see that only as a read param, can't find the place where it is written. is it coming automatically from rethinkdb?

**Comment by belucid** [comment]
@bago2k4 I'm not sure what you mean by :updated-company and :updated-report. I don't see those. Do you mean :updated-at?

```json
{
  "name" : "Transparency, LLC",
  "currency" : "USD",
  "web" : {
    "about" : "https://opencompany.io/about"
  },
  "symbol" : "OPEN",
  "created-at" : "2015-07-31T15:55:54Z",
  "updated-at" : "2015-08-02T10:47:20Z",
  "links" : [ {
    "rel" : "self",
    "method" : "GET",
    "href" : "/v1/companies/OPEN",
    "type" : "application/vnd.open-company.company+json;version=1"
  }, {
    "rel" : "update",
    "method" : "PUT",
    "href" : "/v1/companies/OPEN",
    "type" : "application/vnd.open-company.company+json;version=1"
  }, {
    "rel" : "delete",
    "method" : "DELETE",
    "href" : "/v1/companies/OPEN"
  }, {
    "rel" : "report",
    "method" : "GET",
    "href" : "/v1/companies/OPEN/2015/Q2",
    "type" : "application/vnd.open-company.report+json;version=1"
  } ]
}
```

**Comment by bago2k4** [comment]
nope, it is in the code, the response of the update contains a key called `:updated-company` that is what you give back to the PUT request:
https://github.com/open-company/open-company-api/pull/7/files#diff-2ac019f86342170f95592e611e772ac9R36

i was just wondering where this key is set

**Comment by belucid** [comment]
@bago2k4 Oh, I see. That's not in the response, that's in the context that Liberator is using. See [here](https://clojure-liberator.github.io/liberator/doc/execution-model.html).

Each decision and action function in our resources (such as `:handle-ok?`, `:new?`, `:put!`, etc.) that returns a map has the map they returned deep merged into the Liberator context, and the Liberator context is passed to each decision and action function. It's how you can "communicate" between one function and another... or to think of it another way, it's how all the tiny decisions and actions that happen can build up to the correct behavior and response.

So... where `:updated-company` and `:updated-report` come from is, we put them there, in the context, as the return value of the `put-company` and `put-resource` functions that we call in the `:put` action of the `company` and `report` resources.

We then use the `:updated-company` and `:updated-report` key/value to render the response to the `PUT` request in the `:handle-ok` for `:put` handler of the two resources.

**Pull request merged**
