### PR TITLE
Initial API implementation for companies and reports

### PR DESCRIPTION
**Pull request by belucid**
To test:
0. Follow the README to deal w/ any dependencies
1. Follow the README to create the DB and indexes
2. Follow the README to start the API
3. Follow the README to create the DB, tables and indexes at the REPL.
4. Run the cURL examples from the README.

No automatic DB setup yet. Coming soon.

No test support yet. Coming soon.

No data validation yet. Coming soon.

No default values yet. Coming soon.

No time stamps yet. Coming soon.

No cascading deletes from company to reports yet. Coming soon.

No logging yet.

No PATCH support yet.

### CODE REVIEW

**Comment by belucid** [comment]
Also: https://trello.com/c/cYJ2taAi

To verify CORS support, add `--header "Origin: http://example.com"` to your cURL request.

Example:

```console
curl -i -X GET \
--header "Origin: http://example.com" \
--header "Accept: application/vnd.open-company.company+json;version=1" \
--header "Accept-Charset: utf-8" \
http://localhost:3000/v1/companies/OPEN
```

Look for `Access-Control-Allow-Origin: http://example.com` in the response. See it? Good! CORs is working.

**Comment by belucid** [comment]
Also: https://trello.com/c/IEJtdefT

To verify Sentry support, start up the API server as is:

```console
lein start
```

Notice the console output says: `Sentry: false`

Good! That's cause it's not configured.

No startup the API Server with the DSN for the open-company-api project as an env var:

```console
DSN=<insert here> lein start
```

Then insert a bug in the code. Such as add this to `open-company.api.companies.clj` at line 23 1/2:

```clojure
(/ 0 42)
```

Then use the API with cURL:

```console
curl -i -X GET \
--header "Accept: application/vnd.open-company.company+json;version=1" \
--header "Accept-Charset: utf-8" \
http://localhost:3000/v1/companies/OPEN
```

Verify you get a new divide by zero error in Sentry. You do? Splendid.

**Comment by bago2k4** [comment]
All the test described above wrok, not sure how to run the unit tests. Running `lein test` result in these errors:
```console
$ lein test
WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
^Cbago@iacopos-MacBook-Pro:open-company-api (initial)*
$ lein test
WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update

FAIL "about using the REST API to create valid new companies - when the ticker symbol in the body and the URL match" at (company_create.clj:77)
    Expected: 201
      Actual: 200

FAIL "about using the REST API to create valid new companies - when the ticker symbol in the body and the URL match" at (company_create.clj:78)
    Expected: "application/vnd.open-company.company+json;version=1"
      Actual: "application/vnd.open-company.company+json"
       Diffs: strings have 1 difference (80% similarity)
                expected: "...y+json(;version=1)"
                actual:   "...y+json(----------)"

FAIL "about using the REST API to create valid new companies - when the ticker symbol in the body and the URL match" at (company_create.clj:79)
    Expected: "/v1/companies/OPEN"
      Actual: nil

FAIL in clojure.lang.PersistentList$EmptyList@1 (hateoas.clj:21)

expected: 3
  actual: 4

expected: 4 to be an instance of java.lang.Integer
     was: 4 is an instance of java.lang.Long
       Exception in thread "main" java.lang.AssertionError: Assert failed: (clojure.test/is (= (count links) 4)), compiling:(open_company/integration/company/company_create.clj:59:1)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at user$eval4479.invoke(form-init809800109222095316.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.AssertionError: Assert failed: (clojure.test/is (= (count links) 4))
	at open_company.lib.hateoas$verify_company_links.invoke(hateoas.clj:21)
	at open_company.integration.company.company_create$eval26055$fn__26056$fn__26057$fn__26058$fn__26059$fn__26060$fn__26061.invoke(company_create.clj:60)
	at midje.util.thread_safe_var_nesting$with_altered_roots_STAR_.invoke(thread_safe_var_nesting.clj:32)
	at open_company.integration.company.company_create$eval26055$fn__26056$fn__26057$fn__26058$fn__26059$fn__26060.invoke(company_create.clj:60)
	at open_company.integration.company.company_create$eval26055$fn__26056$fn__26057$fn__26058$fn__26059.invoke(company_create.clj:60)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at midje.checking.facts$check_one$fn__8891.invoke(facts.clj:21)
	at midje.checking.facts$check_one.invoke(facts.clj:20)
	at midje.checking.facts$creation_time_check.invoke(facts.clj:35)
	at open_company.integration.company.company_create$eval26055$fn__26056$fn__26057$fn__26058.invoke(company_create.clj:60)
	at midje.util.thread_safe_var_nesting$with_altered_roots_STAR_.invoke(thread_safe_var_nesting.clj:32)
	at open_company.integration.company.company_create$eval26055$fn__26056$fn__26057.invoke(company_create.clj:60)
	at open_company.integration.company.company_create$eval26055$fn__26056.invoke(company_create.clj:60)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at midje.checking.facts$check_one$fn__8893.invoke(facts.clj:31)
	at midje.checking.facts$check_one.invoke(facts.clj:30)
	at midje.checking.facts$creation_time_check.invoke(facts.clj:35)
	at open_company.integration.company.company_create$eval26055.invoke(company_create.clj:60)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 33 more
Tests failed.
```

Other than this it looks good

**Comment by belucid** [comment]
@bago2k4 the unit tests aren't ready, they are a separate card https://trello.com/c/LIkQTTyw and https://trello.com/c/VMo3x650

**Pull request merged**
