### PR TITLE
Section update authorship

### PR DESCRIPTION
**Pull request by belucid**
https://trello.com/c/PyfjkhgZ

To test:

Make some normal API requests with no authorization, note you get a 401:

```
curl -i -X GET http://localhost:3000/companies
```

```
curl -i -X GET http://localhost:3000/companies/buffer
```

Now make the same API calls as a logged in user in the UI which passes JWT credentials and note that you can see the company list and the buffer data.

Now edit one of the text sections of the buffer data. Then refresh the page (there's a UI bug) and see that the update was attributed to your logged in user. Pull the same section from the Clojure API and see that the `:author` is you:

```clojure
(section/get-company "buffer" "update")
```

Next rerun the sample data import (with delete flag) for `buffer.edn`, `mature.edn`, `new.edn` and `yoyo.edn`. Notice they have authors that aren't Stuart? Super.

Study the code with a critical eye. All is well? Merge.

After deploying to staging, run the import with delete on staging for `buffer.edn`, `mature.edn`, `new.edn` and `yoyo.edn`.

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 this is ready for you.

**Comment by bago2k4** [comment]
reviewing

**Comment by bago2k4** [comment]
@belucid so everything looks good until i run the import again, from that time the companies i reimported don't appear in the companies list and i get a 404 if i try to get a company by slug.
Import script:
```console
$ lein run -m open-company.util.sample-data -- -d ./opt/samples/buffer.edn
Creating company 'buffer'.
Creating section 'values' at: 2015-06-08T12:35:19Z
Creating section 'mission' at: 2015-06-22T18:33:41Z
Creating section 'finances' at: 2015-07-13T12:59:28Z
Creating section 'update' at: 2015-07-13T12:59:31Z
Creating section 'asks' at: 2015-07-13T12:59:32Z
Creating section 'team' at: 2015-07-13T12:59:33Z
Creating section 'product' at: 2015-07-13T12:59:34Z
Creating section 'finances' at: 2015-08-13T16:26:41Z
Creating section 'asks' at: 2015-08-13T16:26:43Z
Creating section 'update' at: 2015-08-13T16:26:44Z
Creating section 'team' at: 2015-08-13T16:26:45Z
Creating section 'product' at: 2015-08-13T16:26:46Z
Creating section 'finances' at: 2015-09-18T18:33:41Z
Creating section 'asks' at: 2015-09-18T18:33:43Z
Creating section 'update' at: 2015-09-18T18:33:44Z
Creating section 'team' at: 2015-09-18T18:33:45Z
Creating section 'product' at: 2015-09-18T18:33:46Z

Import complete!
```
From the repl i get nothing:
```console
open-company.app=> (company/get-company "buffer")
nil
open-company.app=> (section/get-section "buffer" "update")
nil
```

**Comment by bago2k4** [comment]
Never mind the above comment, i was running outdated code

**Pull request merged**
